In [1]:
# 05_ml_실습03_교차검증
# 실습01

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# 붓꽃 데이터셋 로딩
df = pd.read_csv('./datasets/seaborn-data/iris.csv')

# 데이터 분석 I - 통계
# display(df.info())
# display(df.describe())

# 데이터 분석 II - 시각화
# sns.pairplot(df1[['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']], hue='species')
# plt.scatter(df1['petal_length'], df1['petal_width'], cmap=plt.cm.RdYlGn, s=100, c=df1['label'])
# plt.show()

In [20]:
# 전처리 - 사이킥-런
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

df1 = df.copy()
# 라벨 인코딩
lb_encoder = LabelEncoder()
lb_encoder.fit(df1['species'])
labels = lb_encoder.transform(df1['species'])

display(lb_encoder.classes_)
df1['label'] = labels
display(df1.head(5))

array(['setosa', 'versicolor', 'virginica'], dtype=object)

   sepal_length  sepal_width  petal_length  petal_width species  label
0           5.1          3.5           1.4          0.2  setosa      0
1           4.9          3.0           1.4          0.2  setosa      0
2           4.7          3.2           1.3          0.2  setosa      0
3           4.6          3.1           1.5          0.2  setosa      0
4           5.0          3.6           1.4          0.2  setosa      0

In [34]:
# 원샷 인코딩
df2 = df.copy()
# 2차원 변환
labels = labels.reshape(-1, 1)

oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels = oh_encoder.transform(labels)

# 데이터 프레임 만들기
df3 = pd.DataFrame(oh_labels.toarray(), columns=lb_encoder.classes_, dtype=int)
display(df3)

df4 = pd.concat([df2, df3], axis=1)
display(df4.head(5))

     setosa  versicolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

,sepal_length,sepal_width,petal_length,petal_width,species,setosa,versicolor,virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0

In [35]:
print(type(df4))

<class 'pandas.core.frame.DataFrame'>

In [32]:
# 학습(Decision Tree)
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split, KFold, StratifiedKFold

# 학습 데이터 만들기
# df1 = df1.drop(['species'], axis=1)
# x_df = df1.drop(['label'], axis=1)
# y_df = df1.label

# display(y_df)
# display(x_df)

display(df1.labels)

AttributeError: 'DataFrame' object has no attribute 'labels'

In [14]:
# StratifiedKFold 교차 검증

# 학습, 검증 데이터 추출 
# X_train, X_test, y_train, y_test = train_test_split(x_df, y_df, train_size=0.25, random_state=5)

# skfold = StratifiedKFold(n_splits=7)
kfold = KFold(n_splits=7)
dt_clf = DecisionTreeClassifier(random_state=5)

result = []
# for train_index, test_index in skfold.split(x_df, y_df):
for train_index, test_index in kfold.split(x_df):
    X_train, X_test = x_df[train_index], x_df[test_index]
    y_train, y_test = y_df[train_index], y_df[test_index]

    dt_clf.fit(X_train, y_train)
    y_pred = dt_clf.predict(X_test)

    result.append(accuracy_score(y_test, y_pred))

KeyError: "None of [Int64Index([ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,\n            ...\n            140, 141, 142, 143, 144, 145, 146, 147, 148, 149],\n           dtype='int64', length=128)] are in the [columns]"

In [ ]:

    tran_label, tran_cnt = np.unique(y_train, return_counts=True)
    test_label, test_cnt = np.unique(y_test, return_counts=True)

    print(f'학습 레이블: {tran_label}, 개수: {tran_cnt}')
    print(f'검증 레이블: {test_label}, 개수: {test_cnt}')

for i, value in result:
    print(f'교차 검증 {i} 번째 학습의 정확도: {value:0.2f}')

print(f'평균 정확도: {np.array(result).mean():0.2f}')



# 학습 : 모델 I. 의사결정 트리


dt_clf.fit(X_train, y_train)
y_pred = dt_clf.predict(X_test)
display(y_pred)

# 평가
from sklearn.metrics import accuracy_score

print('의사결정 트리 예측 정확도: {0:.4f}'.format(accuracy_score(y_test, y_pred)))



# 학습 : 모델 II. 로지스틱 회귀분석
from sklearn.linear_model import LogisticRegression

dt_lr = LogisticRegression(random_state=10)

dt_lr.fit(X_train, y_train)
y_pred = dt_lr.predict(X_test)

# 평가
print('로지스틱 예측 정확도: {0:.4f}'.format(accuracy_score(y_test, y_pred)))